### ISSUE TITLE
Leverage EOSIO as your blockchain protocol?

### ISSUE THREAD

**Issue by DenisCarriere** [OpenPlaceReviews/opendb#7]
I would like to introduce this idea, feel free to reject or accept this idea.

Would it be possible to leverage the EOSIO protocol for your blockchain component and focus your development energy on building robust smart contracts that would allow OpenPlaceReviews to operate on a scalable & global existing chain.

The smart contract development in EOSIO is written in C++ however a lot of the complexity have been abstracted by the [EOSIO CDT (Contract Developer Toolkit)](https://github.com/EOSIO/eosio.cdt) which allows you to quickly & easily build efficient smart contract code which operates on a decentralized network.

There are tons of developer documentation that can be found here: https://developers.eos.io

I'd be willing to help out with the smart contract development and the OpenPlaceReviews EOSIO integration.

CC: @vshcherb

**Comment by vshcherb** [comment]
Thanks, indeed it is interesting idea though we plan to not put on a generic public chain in order to reduce our costs to store data to practially 0$, probably 0.1$ per GB of data.

**Comment by DenisCarriere** [comment]
100% reasonable feedback, the cost of resources on EOSIO are very affordable, however they do have some costs. I don't think any blockchain has 0.1$/ per GB

Another option is hosting your own EOSIO chain which will make the resources cost drastically lower compared to a public chain.

Using the EOSIO protocol you'll be able to have native mobile support for Swift & Java 
https://medium.com/eosio/eosio-software-release-native-sdks-for-swift-and-java-e6086ddd37b8

Just throwing this idea to be explored
